name: Deploy Lambda Function

# on push, execute a lint job
on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest #this is a GitHub Ubuntu runner
    steps: 
      - name: Check out code
        uses: actions/checkout@v3 #name of a public GH action for code checkout available at https://github.com/marketplace/actions/checkout
      - name: Set up Python
        uses: actions/setup-python@v4 #name of a public GH action for python installation available at https://github.com/marketplace/actions/setup-python
        with:
          python-version: 3.8
      - name: Install libraries
        run: pip install flake8 #install flake8 library
      - name: Lint with flake8
        run: |
            cd function # executes the code lint inside the function folder (parameters are irrelevant for this lab)
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi # uses the requirements.txt paramaters
      - name: Zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
        
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        uses: actions/create-release@v1.10
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release from ${{ github.run_number }}
          body: New release for ${{ github.sha }}. Release notes can be found in the docs.
          draft: false
          prerelease: false
